emp.age: 21
emp.salary: 3150
emp.name: Victor
car.mark: Renault
car.color: black
pet.name: Stephan
pet.kind: cat
spring.datasource.url: jdbc:postgresql://localhost:5432/doctor_pets
spring.datasource.username: postgres
spring.datasource.password: 1234
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.database: postgresql
spring.jpa.hibernate.ddl-auto: update
spring.thymeleaf.enabled: true